import { MessageClassification } from '@/types/message';
import React from 'react';
import WordCloud from 'react-d3-cloud';

export default function Wortwolke({ classifications }: { classifications: MessageClassification[] }) {
  let textArray: string[]= [];
  let wordCountArray: number[] = [];

  const irrelevantWords: string[] = [
    "und",
    "gerne",
    "wieder",
    "sehr",
    "dank",
    "danke",
    "vielen",
    "bestens",
    "immer",
    ",",
    "!",
    ".",
    "alles",
    "super",
    "wie",
    "prima",
    "gut",
    "top",
    "jederzeit",
    "gern",
    "👍",
    "grüße",
    "aus",
    "der ",
    "die ",
    "das",
    "den",
    "des",
    "dem",
    "es ",
    "ist",
    "eine",
    "eines",
    "ein",
    "einer",
    "was",
    "sehr",
    "geehrte",
    "Damen",
    "Herren",
    "ich",
    "kann",
    "nicht",
    "am",
    "habe",
    "mir",
    "wegen",
    "sollte",
    "ja",
    "an",
    "wurde",
    "nur",
    "vor",
    "allem",
    "aber",
    "mit",
    "Sie",
    "sich",
    "?",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "noch",
    "leider",
    "kein",
    "hab",
    "bei",
    "Ihnen",
    "von",
    "keine",
    "gute",
    "guten",
    "schneller",
    "schnellere",
    "schon",
    "um",
    "bitte",
    "ein",
    "zwei",
    "drei",
    "vier",
    "fünf",
    "sechs",
    "sieben",
    "acht",
    "meine",
    "auf",
    "einem",
    " - ",
    "neun",
    "zehn",
    "also",
    "Also",
    "obwohl",
    "freundlichen Grüßen",
    ":",
    "Wir",
    "da",
    "werden",
    "sodaß",
    "sodass",
    "dass",
    "so",
    "erste",
    "TOP",
    "zu",
    "Alles",
    "…",
    "meinen",
    "darum",
    "sowie",
    "ohne",
    "wirklich",
    "ihn",
    "absolut",
    "macht",
    "Dankeschön",
    "Ob",
    "kleine",
    "Hatte",
    "guter",
    "in",
    "ok",
    "OK",
    "dies",
    "hoch",
    "Daumen",
    "Flachproil",
    "genial",
    "toller",
    "what",
    "else",
    "jetzt",
    "i.O.",
    "i.O.!",
    "+",
    "ALLES",
    "1a",
    "war",
    "okay",
    "beste",
    "perfekt!",
    "O.K.",
    "Supi",
    "Bestens!",
    "passt",
    "Danke",
    "Perfect",
    "in Ordnung",
    "*",
    "Gruß",
    "Note 1",
    "sagt",
    "waren",
    "meiner",
    "⭐️",
    "/",
    "Tolle",
    "als",
    "mega",
    "für",
    "ever!",
    "Kam",
    "allen",
    ":-)",
    "Spass",
    "Prozent",
    "muss",
    "sein",
    "mal",
    "%",
    "mußte",
    "(=",
    "Gutes",
    "würde",
    "klasse",
    "VG",
    ";",
    "nix",
    "perfekte",
    "Besser",
    "geht’s",
    "gehts",
    "Tip",
    "Dank!",
    "wieder"
]

  classifications.forEach(c => {
    const classificationWords: any = c.phrase.match(/[a-zA-Z]+/g);
    if(classificationWords){
      classificationWords.forEach((w) => {
        const word = w.toLowerCase();
        const searchIndex = textArray.indexOf(word);
        if (searchIndex === -1) {
          textArray.push(word);
          wordCountArray.push(1);
        } else {
          wordCountArray[searchIndex] = wordCountArray[searchIndex] + 1;
        }
      });
    }
  });

  const data = textArray.map((t,i) => {
    return { text: t, value: wordCountArray[i] }
  })

  const finalData = data.filter(({ text }) => {
    return irrelevantWords.find((iW) => iW.toLowerCase() === text) === undefined;
  })
  .filter(({ value }) => value > 1)
  .filter(({ text }) => text.length !== 1);
  return <WordCloud 
          height={350} 
          data={finalData} 
          
          fontSize={(d) => Math.sqrt(d.value)*5}
        />
}